version: "3.9"
services:
  postgresdb:
    image: "postgres:15.3"
    ports:
      - "5433:5432"
    volumes:
      - ../init_scripts/postgres:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=performancetesting